var concepts =
[
    [ "sleipnir", "namespacesleipnir.html", [
      [ "ScalarLike", "conceptsleipnir_1_1_scalar_like.html", null ],
      [ "SleipnirMatrixLike", "conceptsleipnir_1_1_sleipnir_matrix_like.html", null ],
      [ "EigenMatrixLike", "conceptsleipnir_1_1_eigen_matrix_like.html", null ],
      [ "MatrixLike", "conceptsleipnir_1_1_matrix_like.html", null ],
      [ "EigenSolver", "conceptsleipnir_1_1_eigen_solver.html", null ]
    ] ],
    [ "wpi", "namespacewpi.html", [
      [ "java", "namespacewpi_1_1java.html", [
        [ "detail", "namespacewpi_1_1java_1_1detail.html", [
          [ "JArrayType", "conceptwpi_1_1java_1_1detail_1_1_j_array_type.html", null ]
        ] ]
      ] ],
      [ "memory", "namespacewpi_1_1memory.html", [
        [ "is", "conceptwpi_1_1memory_1_1is.html", null ],
        [ "and", "conceptwpi_1_1memory_1_1and.html", null ],
        [ "that", "conceptwpi_1_1memory_1_1that.html", null ],
        [ "allocations", "conceptwpi_1_1memory_1_1allocations.html", null ],
        [ "defines", "conceptwpi_1_1memory_1_1defines.html", null ],
        [ "the", "conceptwpi_1_1memory_1_1the.html", null ],
        [ "has", "conceptwpi_1_1memory_1_1has.html", null ],
        [ "br", "conceptwpi_1_1memory_1_1br.html", null ],
        [ "or", "conceptwpi_1_1memory_1_1or.html", null ],
        [ "a", "conceptwpi_1_1memory_1_1a.html", null ],
        [ "for", "conceptwpi_1_1memory_1_1for.html", null ],
        [ "as", "conceptwpi_1_1memory_1_1as.html", null ],
        [ "of", "conceptwpi_1_1memory_1_1of.html", null ],
        [ "in", "conceptwpi_1_1memory_1_1in.html", null ],
        [ "adapter", "conceptwpi_1_1memory_1_1adapter.html", null ],
        [ "uses", "conceptwpi_1_1memory_1_1uses.html", null ],
        [ "to", "conceptwpi_1_1memory_1_1to.html", null ],
        [ "It", "conceptwpi_1_1memory_1_1_it.html", null ],
        [ "returns", "conceptwpi_1_1memory_1_1returns.html", null ],
        [ "with", "conceptwpi_1_1memory_1_1with.html", null ]
      ] ],
      [ "ProtobufSerializable", "conceptwpi_1_1_protobuf_serializable.html", null ],
      [ "MutableProtobufSerializable", "conceptwpi_1_1_mutable_protobuf_serializable.html", null ],
      [ "DecayedDerivedFrom", "conceptwpi_1_1_decayed_derived_from.html", null ],
      [ "StructSerializable", "conceptwpi_1_1_struct_serializable.html", null ],
      [ "MutableStructSerializable", "conceptwpi_1_1_mutable_struct_serializable.html", null ],
      [ "HasNestedStruct", "conceptwpi_1_1_has_nested_struct.html", null ]
    ] ],
    [ "with", "conceptwpi_1_1memory_1_1allocator__traits_3_01memory__pool_3_01_pool_type_00_01_impl_raw_allocator_01_4_01_4_1_1with.html", null ],
    [ "doesn", "conceptwpi_1_1memory_1_1binary__segregator_1_1doesn.html", null ],
    [ "to", "conceptwpi_1_1memory_1_1binary__segregator_1_1to.html", null ],
    [ "with", "conceptwpi_1_1memory_1_1composable__allocator__traits_3_01memory__pool_3_01_pool_type_00_01_bloce7ea10f911e03566cad13c14881c07ba.html", null ],
    [ "object", "conceptwpi_1_1memory_1_1fixed__block__allocator_1_1object.html", null ],
    [ "or", "conceptwpi_1_1memory_1_1fixed__block__allocator_1_1or.html", null ],
    [ "object", "conceptwpi_1_1memory_1_1growing__block__allocator_1_1object.html", null ],
    [ "used", "conceptwpi_1_1memory_1_1iteration__allocator_1_1used.html", null ],
    [ "with", "conceptwpi_1_1memory_1_1iteration__allocator_1_1with.html", null ],
    [ "but", "conceptwpi_1_1memory_1_1joint__ptr_1_1but.html", null ],
    [ "will", "conceptwpi_1_1memory_1_1joint__ptr_1_1will.html", null ],
    [ "allocation", "conceptwpi_1_1memory_1_1memory__arena_1_1allocation.html", null ],
    [ "and", "conceptwpi_1_1memory_1_1memory__arena_1_1and.html", null ],
    [ "object", "conceptwpi_1_1memory_1_1memory__arena_1_1object.html", null ],
    [ "but", "conceptwpi_1_1memory_1_1memory__pool_1_1but.html", null ],
    [ "by", "conceptwpi_1_1memory_1_1memory__pool_1_1by.html", null ],
    [ "in", "conceptwpi_1_1memory_1_1memory__pool_1_1in.html", null ],
    [ "of", "conceptwpi_1_1memory_1_1memory__pool_1_1of.html", null ],
    [ "s", "conceptwpi_1_1memory_1_1memory__pool_1_1s.html", null ],
    [ "similar", "conceptwpi_1_1memory_1_1memory__pool_1_1similar.html", null ],
    [ "used", "conceptwpi_1_1memory_1_1memory__pool_1_1used.html", null ],
    [ "will", "conceptwpi_1_1memory_1_1memory__pool_1_1will.html", null ],
    [ "and", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1and.html", null ],
    [ "by", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1by.html", null ],
    [ "if", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1if.html", null ],
    [ "less", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1less.html", null ],
    [ "of", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1of.html", null ],
    [ "s", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1s.html", null ],
    [ "similar", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1similar.html", null ],
    [ "size", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1size.html", null ],
    [ "used", "conceptwpi_1_1memory_1_1memory__pool__collection_1_1used.html", null ],
    [ "needs", "conceptwpi_1_1memory_1_1memory__stack_1_1needs.html", null ],
    [ "on", "conceptwpi_1_1memory_1_1memory__stack_1_1on.html", null ],
    [ "or", "conceptwpi_1_1memory_1_1memory__stack_1_1or.html", null ],
    [ "used", "conceptwpi_1_1memory_1_1memory__stack_1_1used.html", null ],
    [ "with", "conceptwpi_1_1memory_1_1memory__stack_1_1with.html", null ],
    [ "member", "conceptwpi_1_1memory_1_1reference__storage_3_01any__allocator_01_4_1_1member.html", null ],
    [ "allocation", "conceptwpi_1_1memory_1_1static__allocator_1_1allocation.html", null ],
    [ "deallocation", "conceptwpi_1_1memory_1_1static__allocator_1_1deallocation.html", null ],
    [ "it", "conceptwpi_1_1memory_1_1static__allocator_1_1it.html", null ],
    [ "and", "conceptwpi_1_1memory_1_1tracked__allocator_1_1and.html", null ],
    [ "and", "conceptwpi_1_1memory_1_1tracked__block__allocator_1_1and.html", null ],
    [ "allocation", "conceptwpi_1_1memory_1_1virtual__memory__allocator_1_1allocation.html", null ],
    [ "deallocation", "conceptwpi_1_1memory_1_1virtual__memory__allocator_1_1deallocation.html", null ],
    [ "it", "conceptwpi_1_1memory_1_1virtual__memory__allocator_1_1it.html", null ]
];